import type { Metadata } from "next";
import { Inter, Roboto_Mono, Noto_Sans_KR } from "next/font/google";
import "../index.css";
import { styled } from "@styled-system/jsx";
import { flex } from "@styled-system/patterns";
import Image from "next/image";
import hanbyolLogo from "@asset/hbjr_logo.png";

const inter = Inter({ subsets: ["latin"], display: "swap" });
const roboto = Roboto_Mono({ subsets: ["latin"], display: "swap" });
const noto_sans_kr = Noto_Sans_KR({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Menu {
  title: string;
  path: string;
}
const MENU_ARR: Menu[] = [
  { title: "Home", path: "/" },
  { title: "Company Info", path: "/company-info" },
  { title: "Products", path: "/products" },
  { title: "Projects", path: "/projects" },
  { title: "Contact", path: "/contact" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={noto_sans_kr.className}>
        <styled.header
          w="100%"
          h="fit"
          display="flex"
          pt="28px"
          background="transparent"
          position="fixed"
          color="white"
          zIndex={999}
        >
          <styled.div
            paddingX="90px"
            w="100%"
            className={flex({ justify: "space-between" })}
          >
            <div>
              <Image src={hanbyolLogo} alt="Logo"></Image>
            </div>
            <div className={flex()}>
              {MENU_ARR.map((menu) => (
                <styled.a
                  key={menu.path}
                  href={menu.path}
                  pb="45px"
                  pt="17px"
                  marginX="20px"
                  display="inline-block"
                >
                  {menu.title}
                </styled.a>
              ))}
            </div>
          </styled.div>
        </styled.header>
        {children}
      </body>
    </html>
  );
}
